# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/p350/setup-makefiles.sh


## RIL

PRODUCT_COPY_FILES += \
    vendor/lge/p350/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/lge/p350/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/p350/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/lge/p350/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/lge/p350/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/p350/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/lge/p350/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
     vendor/lge/p350/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
     vendor/lge/p350/proprietary/lib/libsnd.so:system/lib/libsnd.so \
     vendor/lge/p350/proprietary/lib/libril.so:system/lib/libril.so \
     vendor/lge/p350/proprietary/bin/qmuxd:system/bin/qmuxd \
     vendor/lge/p350/proprietary/bin/rild:system/bin/rild \
     vendor/lge/p350/proprietary/etc/flex/flex.xml:system/etc/flex/flex.xml \
     vendor/lge/p350/proprietary/lib/libnv.so:system/lib/libnv.so \
     vendor/lge/p350/proprietary/lib/libauth.so:system/lib/libauth.so \
     vendor/lge/p350/proprietary/lib/libwms.so:system/lib/libwms.so \
     vendor/lge/p350/proprietary/lib/libgsl.so:system/lib/libgsl.so \
     vendor/lge/p350/proprietary/lib/libdiag.so:system/lib/libdiag.so \
     vendor/lge/p350/proprietary/lib/libril.so:obj/lib/libril.so \
     vendor/lge/p350/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
     vendor/lge/p350/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
     vendor/lge/p350/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
     vendor/lge/p350/proprietary/lib/liblgeat.so:system/lib/liblgeat.so \
     vendor/lge/p350/proprietary/lib/libcm.so:system/lib/libcm.so \
     vendor/lge/p350/proprietary/lib/libqueue.so:system/lib/libqueue.so \
     vendor/lge/p350/proprietary/lib/liblgerft.so:system/lib/liblgerft.so \
     vendor/lge/p350/proprietary/lib/libdss.so:system/lib/libdss.so \
     vendor/lge/p350/proprietary/lib/libdll.so:system/lib/libdll.so \
     vendor/lge/p350/proprietary/lib/libbcmwl.so:system/lib/libbcmwl.so \
     vendor/lge/p350/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
     vendor/lge/p350/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
     vendor/lge/p350/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
     vendor/lge/p350/proprietary/lib/libsnd.so:system/lib/libsnd.so \
     vendor/lge/p350/proprietary/bin/qmuxd:system/bin/qmuxd \
     vendor/lge/p350/proprietary/etc/flex/flex.xml:system/etc/flex/flex.xml

## Audio

PRODUCT_COPY_FILES += \
    vendor/lge/p350/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so

## HAL
PRODUCT_COPY_FILES += \
    vendor/lge/p350/proprietary/lib/hw/sensors.p350.so:system/lib/hw/sensors.p350.so \
   
## EGL
PRODUCT_COPY_FILES += \
    vendor/lge/p350/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/lge/p350/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/lge/p350/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/lge/p350/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/lge/p350/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/lge/p350/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw

## Sensors
PRODUCT_COPY_FILES += \
    vendor/lge/p350/proprietary/bin/ami304d:system/bin/ami304d

## Camera
PRODUCT_COPY_FILES += \
    vendor/lge/p350/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/lge/p350/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/lge/p350/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/p350/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/p350/proprietary/lib/libmmipl.so:system/lib/libmmipl.so

## BT
PRODUCT_COPY_FILES += \
    vendor/lge/p350/proprietary/etc/firmware/BCM43291A0_003.001.013.0060.Pecan.hcd:system/etc/firmware/BCM43291A0_003.001.013.0060.Pecan.hcd

## WiFi
PRODUCT_COPY_FILES += \
    vendor/lge/p350/proprietary/etc/wl/rtecdc.bin:system/etc/wl/rtecdc.bin \
    vendor/lge/p350/proprietary/etc/wl/rtecdc-apsta.bin:system/etc/wl/rtecdc-apsta.bin
