# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/pecan/setup-makefiles.sh


## RIL

PRODUCT_COPY_FILES += \
    vendor/lge/pecan/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/lge/pecan/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/pecan/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/lge/pecan/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/lge/pecan/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/pecan/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/lge/pecan/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/lge/pecan/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/lge/pecan/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/lge/pecan/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/lge/pecan/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/lge/pecan/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/pecan/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/lge/pecan/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/lge/pecan/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/lge/pecan/proprietary/lib/liblgeat.so:system/lib/liblgeat.so \
    vendor/lge/pecan/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/lge/pecan/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/lge/pecan/proprietary/lib/liblgerft.so:system/lib/liblgerft.so \
    vendor/lge/pecan/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/lge/pecan/proprietary/lib/libbcmwl.so:system/lib/libbcmwl.so \
    vendor/lge/pecan/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/lge/pecan/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/pecan/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
    vendor/lge/pecan/proprietary/lib/libsnd.so:system/lib/libsnd.so \
      vendor/lge/pecan/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/lge/pecan/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/lge/pecan/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/pecan/proprietary/bin/rild:system/bin/rild \
    vendor/lge/pecan/proprietary/etc/flex/flex.xml:system/etc/flex/flex.xml

# vendor/lge/pecan/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so 
# vendor/lge/pecan/proprietary/lib/libidl.so:system/lib/libidl.so 
## Audio

PRODUCT_COPY_FILES += \
    vendor/lge/pecan/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/lge/pecan/proprietary/lib/liba2dp.so:obj/lib/liba2dp.so  \
    vendor/lge/pecan/proprietary/lib/liba2dp.so:system/lib/liba2dp.so 
# vendor/lge/pecan/proprietary/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \

## HAL
PRODUCT_COPY_FILES += \
vendor/lge/pecan/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/lge/pecan/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/lge/pecan/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/lge/pecan/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/lge/pecan/proprietary/lib/egl/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/lge/pecan/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/lge/pecan/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/lge/pecan/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/lge/pecan/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/lge/pecan/proprietary/lib/hw/hwcomposer.default.so:system/lib/hw/hwcomposer.default.so \
    vendor/lge/pecan/proprietary/lib/hw/copybit.default.so:system/lib/hw/copybit.default.so \
    vendor/lge/pecan/proprietary/lib/libmemalloc.so:obj/lib/libmemalloc.so  \
    vendor/lge/pecan/proprietary/lib/libmemalloc.so:system/lib/libmemalloc.so \
    vendor/lge/pecan/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/lge/pecan/proprietary/etc/firmware/a225p5_pm4.fw:system/etc/firmware/a225p5_pm4.fw \
    vendor/lge/pecan/proprietary/etc/firmware/a225_pfp.fw:system/etc/firmware/a225_pfp.fw \
    vendor/lge/pecan/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/lge/pecan/proprietary/etc/firmware/a225_pm4.fw:system/etc/firmware/a225_pm4.fw \
    vendor/lge/pecan/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/lge/pecan/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/lge/pecan/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/lge/pecan/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/lge/pecan/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/lge/pecan/proprietary/lib/libC2D2.so:system/lib/libC2D2.so 


## GPS 
#PRDUCT_COPY_FILES += \
#    vendor/lge/pecan/proprietary/lib/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
#    vendor/lge/pecan/proprietary/lib/hw/gps.pecan.so:system/lib/hw/gps.pecan.so

## Lights 
PRDUCT_COPY_FILES += \
    vendor/lge/pecan/proprietary/lib/hw/lights.default.so:system/lib/hw/lights.default.so \
    vendor/lge/pecan/proprietary/lib/hw/lights.pecan.so:system/lib/hw/lights.pecan.so 

## Sensors
PRODUCT_COPY_FILES += \
    vendor/lge/pecan/proprietary/bin/ami304d:system/bin/ami304d \
    vendor/lge/pecan/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/lge/pecan/proprietary/lib/hw/sensors.pecan.so:system/lib/hw/sensors.pecan.so \
    vendor/lge/pecan/proprietary/lib/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so \

## Camera
PRODUCT_COPY_FILES += \
    vendor/lge/pecan/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/pecan/proprietary/lib/liboemcamera.so:obj/lib/liboemcamera.so \
    vendor/lge/pecan/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/lge/pecan/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/pecan/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so \
    vendor/lge/pecan/proprietary/lib/libcamera_client.so:obj/lib/libcamera_client.so\
    vendor/lge/pecan/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so\
    vendor/lge/pecan/proprietary/lib/libcameraservice.so:obj/lib/libcameraservice.so\
    vendor/lge/pecan/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so
#    vendor/lge/pecan/proprietary/lib/hw/camera.pecan.so:obj/lib/hw/camera.pecan.so\
#    vendor/lge/pecan/proprietary/lib/hw/camera.pecan.so:system/lib/hw/camera.pecan.so

## BT
PRODUCT_COPY_FILES += \
    vendor/lge/pecan/proprietary/etc/firmware/BCM43291A0_003.001.013.0060.Pecan.hcd:system/etc/firmware/BCM43291A0_003.001.013.0060.Pecan.hcd \
    vendor/lge/pecan/proprietary/bin/BCM43291A0_003.001.013.0060.Pecan.hcd:system/bin/BCM43291A0_003.001.013.0060.Pecan.hcd

## WiFi
PRODUCT_COPY_FILES += \
    vendor/lge/pecan/proprietary/etc/wl/rtecdc.bin:system/etc/wl/rtecdc.bin \
    vendor/lge/pecan/proprietary/etc/wl/rtecdc-apsta.bin:system/etc/wl/rtecdc-apsta.bin \
    vendor/lge/pecan/proprietary/bin/dhcpcd:system/bin/dhcpcd 
